#!/bin/bash 
####### 版本更新相关参数 ######
Version=1.00  #版本号 

####### 定义路径及文件名  ######
link_update="https://raw.githubusercontent.com/vincilawyer/Bash/main/install-bash.sh"    #更新检查程序网址
data_name="$HOME/myfile"                                                                 #应用数据文件夹位置路径                   
data_path="$data_name/vinci_source"                                                      #应用数据文件夹位置名

##### 更新脚本初始化  #######
function  Initialvinci {
####### Android系统基本参数 ######
      if uname -a | grep -q 'Android'; then echo '检测系统为Android，正在配置中...'     
def_path="/data/data/com.termux/files/usr/bin"     #新下载脚本目录路径
file_link="https://raw.githubusercontent.com/vincilawyer/Bash/main/Android/Android.sh"          # vinci脚本下载网址

     InitialAndroid                                                                              #安卓系统初始化
####### Debian系统基本参数 ######
      elif uname -a | grep -q 'Debian'; then echo '检测系统为Debian，正在配置中...'
def_path="/usr/local/bin"     #新下载脚本目录路径
file_link="https://raw.githubusercontent.com/vincilawyer/Bash/main/Vultr-Debian11/Vultr-Debian11.sh"  

###### 其他系统 ######
      else echo '未知系统，正在配置默认脚本中...'
def_path="/usr/local/bin"     #新下载脚本目录路径
file_link="https://raw.githubusercontent.com/vincilawyer/Bash/main/Vultr-Debian11/Vultr-Debian11.sh" 
      fi
def_name="vinci"                  #主脚本默认名称
file_path="$def_path/$def_name"   #文件保存路径
name="$def_name脚本"   
}


